import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideMenu from "@/sidemenu";
import InfoPanel from "@/infopenal";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col md:flex-row h-screen">
          <SideMenu />
          <div className="flex-1 md:w-[70%] p-6 flex flex-col items-center justify-center text-center">
            {children}
          </div>
          <InfoPanel/>
        </div>
      </body>
    </html>
  );
}
